mod compiler;
mod ir;
mod lexer;
mod parser;
mod renderer;

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use compiler::{compile_events, project_root_for};
use parser::parse_source;

#[derive(Debug, Parser)]
#[command(name = "malison")]
#[command(version)]
#[command(about = "Executable scores for dark electronic music")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Parse and validate without rendering.
    Check { file: PathBuf },
    /// Validate and print deterministic JSON IR.
    Ir { file: PathBuf },
    /// Validate and print deterministic JSON events.
    Events { file: PathBuf },
    /// Validate and print a deterministic JSON graph.
    Graph { file: PathBuf },
    /// Inspect event expansion in a human-readable form.
    Scry { file: PathBuf },
    /// Compile and render audio.
    Render {
        file: PathBuf,
        #[arg(long)]
        out: Option<PathBuf>,
        #[arg(long, default_value = "rust")]
        backend: String,
        #[arg(long)]
        seed: Option<String>,
        #[arg(long, default_value_t = 48000)]
        sample_rate: u32,
        #[arg(long, default_value_t = 24)]
        bit_depth: u16,
        #[arg(long)]
        dry_run: bool,
        #[arg(long)]
        force: bool,
    },
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error[{}]: {error:#}", diagnostic_code(&error));
            ExitCode::FAILURE
        }
    }
}

fn diagnostic_code(error: &anyhow::Error) -> &'static str {
    let message = error.to_string();
    if message.contains("unresolved daemon") || message.contains("unresolved spell") {
        "E021"
    } else if message.contains("unsupported")
        || message.contains("expected")
        || message.contains("unexpected")
        || message.contains("unterminated")
        || message.contains("reserved word")
    {
        "E001"
    } else if message.contains("backend") || message.contains("SuperCollider") {
        "E080"
    } else if message.contains("parameter")
        || message.contains("tempo")
        || message.contains("meter")
        || message.contains("must")
        || message.contains("duplicate")
    {
        "E030"
    } else if message.contains("output") || message.contains("failed to read") {
        "E070"
    } else {
        "E000"
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Check { file } => {
            load_and_compile(&file)?;
            Ok(())
        }
        Command::Ir { file } => {
            let compiled = load_and_compile(&file)?;
            println!("{}", serde_json::to_string_pretty(&compiled.ir)?);
            Ok(())
        }
        Command::Events { file } => {
            let compiled = load_and_compile(&file)?;
            println!("{}", serde_json::to_string_pretty(&compiled.ir)?);
            Ok(())
        }
        Command::Graph { file } => {
            let compiled = load_and_compile(&file)?;
            println!("{}", serde_json::to_string_pretty(&compiled.ir.graph())?);
            Ok(())
        }
        Command::Scry { file } => {
            let compiled = load_and_compile(&file)?;
            print_scry(&compiled);
            Ok(())
        }
        Command::Render {
            file,
            out,
            backend,
            seed,
            sample_rate,
            bit_depth,
            dry_run,
            force,
        } => {
            if !matches!(backend.as_str(), "rust" | "supercollider") {
                anyhow::bail!("backend `{backend}` is not supported in language 0.1");
            }

            let mut compiled = load_and_compile(&file)?;
            if let Some(seed) = seed {
                compiled.ir.seed = seed;
            }

            let out_path = out.unwrap_or_else(|| compiled.evoke_wav.clone());
            let out_path = if out_path.is_relative() {
                compiled.project_root.join(out_path)
            } else {
                out_path
            };
            if dry_run {
                if backend == "supercollider" {
                    let script = renderer::supercollider_script(
                        &compiled,
                        &out_path,
                        sample_rate,
                        bit_depth,
                    )?;
                    println!("{script}");
                } else {
                    println!(
                        "// Generated by Malison 0.1\n// backend: rust\n// working: {}\n// output: {}\n// events: {}\n",
                        compiled.ir.working,
                        out_path.display(),
                        compiled.ir.events.len()
                    );
                }
                return Ok(());
            }

            if out_path.exists() && !force {
                anyhow::bail!(
                    "output `{}` already exists; pass --force to overwrite",
                    out_path.display()
                );
            }
            compiler::validate_output_path(&out_path)?;

            if backend == "supercollider" {
                return renderer::render_supercollider(
                    &compiled,
                    &out_path,
                    sample_rate,
                    bit_depth,
                );
            }

            renderer::render_wav(&compiled, &out_path, sample_rate, bit_depth)
        }
    }
}

fn load_and_compile(path: &Path) -> Result<compiler::CompiledWorking> {
    if path.extension().and_then(|ext| ext.to_str()) != Some("rite") {
        anyhow::bail!(
            "source file `{}` must use the .rite extension",
            path.display()
        );
    }
    let source =
        fs::read_to_string(path).with_context(|| format!("failed to read `{}`", path.display()))?;
    let working =
        parse_source(path, &source).map_err(|error| with_source_snippet(path, &source, error))?;
    let project_root = project_root_for(path)?;
    compile_events(path, &project_root, working)
        .map_err(|error| with_source_snippet(path, &source, error))
}

fn with_source_snippet(path: &Path, source: &str, error: anyhow::Error) -> anyhow::Error {
    let message = error.to_string();
    let Some((line, column)) = parse_leading_span(&message) else {
        return error;
    };
    let Some(source_line) = source.lines().nth(line.saturating_sub(1)) else {
        return error;
    };
    let line_number = line.to_string();
    let gutter = " ".repeat(line_number.len());
    anyhow::anyhow!(
        "{message}\n--> {}:{line}:{column}\n{line_number} | {source_line}\n{gutter} | {}^",
        path.display(),
        " ".repeat(column.saturating_sub(1))
    )
}

fn parse_leading_span(message: &str) -> Option<(usize, usize)> {
    let (line, rest) = message.split_once(':')?;
    let (column, _) = rest.split_once(':')?;
    Some((line.parse().ok()?, column.parse().ok()?))
}

fn print_scry(compiled: &compiler::CompiledWorking) {
    let ir = &compiled.ir;
    println!("working: {}", ir.working);
    println!("language: {}", ir.language);
    println!("tempo: {} bpm", ir.tempo_bpm);
    println!("meter: {}/{}", ir.meter[0], ir.meter[1]);
    println!("duration: {} beats", ir.duration_beats);
    println!("daemons: {}", ir.daemons.len());
    println!("spells: {}", ir.spells.len());
    println!("rites: {}", ir.rites.len());
    println!("control events: {}", ir.control_events.len());
    println!("events: {}", ir.events.len());
    for rite in &ir.rites {
        println!(
            "\nrite {}: start {} beats, duration {} beats",
            rite.id, rite.start_beats, rite.duration_beats
        );
        for event in ir.events.iter().filter(|event| {
            event.time_beats >= rite.start_beats
                && event.time_beats < rite.start_beats + rite.duration_beats
        }) {
            if let Some(pitch) = &event.pitch {
                println!(
                    "  {:>7.3} {:<7} {:<12} velocity {:>4.2} pitch {} ({})",
                    event.time_beats,
                    event.kind,
                    event.daemon,
                    event.velocity,
                    pitch.name,
                    pitch.midi
                );
            } else {
                println!(
                    "  {:>7.3} {:<7} {:<12} velocity {:>4.2}",
                    event.time_beats, event.kind, event.daemon, event.velocity
                );
            }
        }
        for control in ir.control_events.iter().filter(|control| {
            control.start_beats >= rite.start_beats
                && control.start_beats < rite.start_beats + rite.duration_beats
        }) {
            println!(
                "  {:>7.3} control {:<12} {:>4.2} -> {:>4.2}",
                control.start_beats, control.target, control.from, control.to
            );
        }
    }
}
